# Generated by Django 3.2.7 on 2021-10-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_auto_20211003_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extra',
            old_name='Ingredient',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='extra',
            old_name='Order_Item',
            new_name='order_item',
        ),
        migrations.RenameField(
            model_name='extra',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='order_item',
            name='extras',
            field=models.ManyToManyField(through='pizzas.Extra', to='pizzas.Ingredient'),
        ),
    ]
