# Generated by Django 3.2.7 on 2021-10-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20211003_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
