# Generated by Django 3.2.7 on 2021-10-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_alter_extra_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
