# Generated by Django 3.2.7 on 2021-10-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_ingredient_vegetarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('1', 'customer'), ('2', 'employee'), ('3', 'delivery person')], default='1', max_length=100),
        ),
    ]
