# Generated by Django 3.2.7 on 2021-10-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0007_auto_20211004_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_person',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
