# Generated by Django 3.2.7 on 2021-10-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0011_drink_dessert_drink_dessert_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'incomplete'), ('2', 'in preparation'), ('3', 'on the way'), ('4', 'completed'), ('5', 'cancelled')], default='1', max_length=100),
        ),
    ]
