# Generated by Django 3.2.7 on 2021-10-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='drinks_desserts',
            field=models.ManyToManyField(through='pizzas.Drink_Dessert_Item', to='pizzas.Drink_Dessert'),
        ),
    ]
