# Generated by Django 3.2.7 on 2021-10-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0013_order_drinks_desserts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=6)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
