# Generated by Django 3.2.7 on 2021-10-07 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0014_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount_code',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzas.order'),
        ),
        migrations.AddField(
            model_name='discount_code',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
