# Generated by Django 3.2.7 on 2021-10-11 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0017_order_date_picked_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_picked_up',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzas.delivery_person'),
        ),
    ]
