# Generated by Django 3.2.7 on 2021-10-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0020_alter_dish_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(through='pizzas.Dish_Item', to='pizzas.Ingredient'),
        ),
    ]
